server:
  port: 8082
spring:
  redis:
    host: 192.168.142.142
    port: 6379
    password: kwygugdu19930408
    database: 0
  datasource:
    username: root
    password: kwygugdu19930408
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.142.142:3306/huawei?useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: org.com.entity
  mapper-locations: classpath:mapper/*.xml
AccessKey:
  ID: LTAI5tF7FuBys7ekm9RuPSFr
  Secret: LP6nhxtTr3cRIJvi9gVOTFCwktYWsY
SignName: 李东升个人网站短信验证
TemplateCode: SMS_204760811